"""Added WhiteListed Domians

Revision ID: 61e90658ddfb
Revises: 9ec935506c16
Create Date: 2026-06-07 13:26:52.458318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e90658ddfb'
down_revision: Union[str, Sequence[str], None] = '9ec935506c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelisted_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain', name='uq_user_domain')
    )
    op.create_index(op.f('ix_whitelisted_domains_domain'), 'whitelisted_domains', ['domain'], unique=False)
    op.create_index(op.f('ix_whitelisted_domains_id'), 'whitelisted_domains', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whitelisted_domains_id'), table_name='whitelisted_domains')
    op.drop_index(op.f('ix_whitelisted_domains_domain'), table_name='whitelisted_domains')
    op.drop_table('whitelisted_domains')
    # ### end Alembic commands ###
